spring:
  application:
    name: LIBRARY-SERVICE
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        hbm2ddl.auto: validate
    open-in-view: false
  mvc:
    format:
      date: iso
      date-time: iso
      time: iso
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: by.sergo.book.app.domain.dto.*

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

server:
  forward-headers-strategy: framework
  port: 8082