server:
  port: 9898
spring:
  application:
    name:   IDENTITY-SERVICE
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQL10Dialect

        hbm2ddl.auto: validate
    open-in-view: false
  mvc:
    format:
      date: iso
      date-time: iso
      time: iso
eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka