server:
  port: 8765
spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:



       - id: api-docs
         uri: lb://API-GATEWAY
         predicates:
           - Path=/v3/api-docs

       - id: book-service
         uri: lb://BOOK-SERVICE
         predicates:
          - Path=/v3/api-docs/*, /api/v1/orders/**, /api/v1/authors/**, /api/v1/books/**, /api/v1/genres/**, /api/v1/users/**, /api/v1/userdetails/**
         filters:
          - AuthenticationFilter

       - id: library-service
         uri: lb://LIBRARY-SERVICE
         predicates:
          - Path=/api/v1/idbooks/**, /api/v1/rentaldates/**
         filters:
          - AuthenticationFilter

       - id: identity
         uri: lb://IDENTITY-SERVICE
         predicates:
          - Path=/auth/**
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
springdoc:
  enable-native-support: true
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /v3/api-docs
        name: API Gateway Service
        primaryName: API Gateway Service
      - url: /book-service/v3/api-docs
        name: Book Service
        primaryName: Book Service
      - url: /library-service/v3/api-docs
        name: Library Service
        primaryName: Library Service

logging:
  level:
    org:
      springframework:
        cloud.gateway: info



eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true

#      spring.cloud.gateway.discovery.locator.enabled=true
#      spring.cloud.gateway.discovery.locator.lower-case-service-id=true


